/**
 * OOPSBannerApp UC2 - Banner Display Application
 * 
 * This class demonstrates the creation of a visual banner displaying the word "OOPS" using ASCII art composed of astrisks (*) and spaces. The banner is printed to the console using the individual print statements for each line, crearing a decorative text effect.
 * <p>The banner is generated by printing predefined string patterns line by line, where each line contributes to forming the letters O, O, P, and S in a stlyised format.This extends a basic user story by adding visual presentation to a simple message out[ut.
 * </p>
 * 
 * @author Developer
 * @version 2.0
 */
public class OOPSBannerApp{
    public static void main(String[] args) {
        System.out.println("   ***   "+"   ***   "+"******   "+"   ******");
        System.out.println(" **   ** "+" **   ** "+"**    ** "+" **      ");
        System.out.println("**     **"+"**     **"+"**     **"+"**       ");
        System.out.println("**     **"+"**     **"+"**    ** "+" **      ");
        System.out.println("**     **"+"**     **"+"******   "+"   ***   ");
        System.out.println("**     **"+"**     **"+"**       "+"      ** ");
        System.out.println("**     **"+"**     **"+"**       "+"       **");
        System.out.println(" **   ** "+" **   ** "+"**       "+"      ** ");
        System.out.println("   ***   "+"   ***   "+"**       "+"******   ");
    }
}
